/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'finished' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'refundQr' : IDL.Vec(IDL.Nat8),
  'gameUid' : IDL.Text,
  'gameName' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const PlayerInfo = IDL.Record({
  'playerId' : IDL.Text,
  'registrationDetails' : UserProfile,
});
export const Match = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : MatchStatus,
  'participants' : IDL.Vec(IDL.Principal),
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'joinedPlayers' : IDL.Vec(PlayerInfo),
  'paymentAmount' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Payment = IDL.Record({
  'status' : PaymentStatus,
  'submissionTime' : Time,
  'proofScreenshot' : IDL.Opt(ExternalBlob),
  'amount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'refundStatus' : IDL.Opt(IDL.Text),
  'time' : Time,
  'user' : IDL.Principal,
  'matchId' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePayment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([IDL.Text, Time, IDL.Nat, IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchParticipants' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlayerInfo)],
      ['query'],
    ),
  'getPayment' : IDL.Func([IDL.Principal], [Payment], ['query']),
  'getPaymentStatus' : IDL.Func([IDL.Principal], [PaymentStatus], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidPhoneNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'joinMatch' : IDL.Func([IDL.Text], [], []),
  'promoteToUser' : IDL.Func([IDL.Principal], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'rejectPayment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPayment' : IDL.Func([IDL.Text, IDL.Nat, ExternalBlob], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'finished' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'refundQr' : IDL.Vec(IDL.Nat8),
    'gameUid' : IDL.Text,
    'gameName' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const PlayerInfo = IDL.Record({
    'playerId' : IDL.Text,
    'registrationDetails' : UserProfile,
  });
  const Match = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : MatchStatus,
    'participants' : IDL.Vec(IDL.Principal),
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'joinedPlayers' : IDL.Vec(PlayerInfo),
    'paymentAmount' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Payment = IDL.Record({
    'status' : PaymentStatus,
    'submissionTime' : Time,
    'proofScreenshot' : IDL.Opt(ExternalBlob),
    'amount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'refundStatus' : IDL.Opt(IDL.Text),
    'time' : Time,
    'user' : IDL.Principal,
    'matchId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePayment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func([IDL.Text, Time, IDL.Nat, IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchParticipants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlayerInfo)],
        ['query'],
      ),
    'getPayment' : IDL.Func([IDL.Principal], [Payment], ['query']),
    'getPaymentStatus' : IDL.Func([IDL.Principal], [PaymentStatus], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidPhoneNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'joinMatch' : IDL.Func([IDL.Text], [], []),
    'promoteToUser' : IDL.Func([IDL.Principal], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'rejectPayment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPayment' : IDL.Func([IDL.Text, IDL.Nat, ExternalBlob], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };