/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Match {
  'id' : string,
  'startTime' : Time,
  'status' : MatchStatus,
  'participants' : Array<Principal>,
  'duration' : bigint,
  'name' : string,
  'joinedPlayers' : Array<PlayerInfo>,
  'paymentAmount' : bigint,
}
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'finished' : null };
export interface Payment {
  'status' : PaymentStatus,
  'submissionTime' : Time,
  'proofScreenshot' : [] | [ExternalBlob],
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PlayerInfo {
  'playerId' : string,
  'registrationDetails' : UserProfile,
}
export type Time = bigint;
export interface Transaction {
  'paymentStatus' : PaymentStatus,
  'refundStatus' : [] | [string],
  'time' : Time,
  'user' : Principal,
  'matchId' : string,
  'amount' : bigint,
}
export interface UserProfile {
  'refundQr' : Uint8Array,
  'gameUid' : string,
  'gameName' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePayment' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[string, Time, bigint, bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchParticipants' : ActorMethod<[string], Array<PlayerInfo>>,
  'getPayment' : ActorMethod<[Principal], Payment>,
  'getPaymentStatus' : ActorMethod<[Principal], PaymentStatus>,
  'getTransactionHistory' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isValidPhoneNumber' : ActorMethod<[string], boolean>,
  'joinMatch' : ActorMethod<[string], undefined>,
  'promoteToUser' : ActorMethod<[Principal], undefined>,
  'registerUser' : ActorMethod<[string, string, string, Uint8Array], undefined>,
  'rejectPayment' : ActorMethod<[Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPayment' : ActorMethod<[string, bigint, ExternalBlob], undefined>,
  'updateUserProfile' : ActorMethod<
    [Principal, string, string, string, Uint8Array],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];